name: Deploy Backend & Frontend to Hostinger

on:
  push:
    branches:
      - main  # Change to your main branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v2

      # 📌 Debug GitHub Secrets (Ensure secrets are properly set)
      - name: 🔍 Debug Secrets
        run: |
          [[ -n "${{ secrets.FTP_SERVER }}" ]] && echo "✅ FTP_SERVER is set!" || echo "❌ FTP_SERVER is missing!"
          [[ -n "${{ secrets.FTP_USERNAME }}" ]] && echo "✅ FTP_USERNAME is set!" || echo "❌ FTP_USERNAME is missing!"
          [[ -n "${{ secrets.FTP_PASSWORD }}" ]] && echo "✅ FTP_PASSWORD is set!" || echo "❌ FTP_PASSWORD is missing!"
          [[ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]] && echo "✅ SSH_PRIVATE_KEY is set!" || echo "❌ SSH_PRIVATE_KEY is missing!"
          [[ -n "${{ secrets.SSH_DOMAIN }}" ]] && echo "✅ SSH_DOMAIN is set!" || echo "❌ SSH_DOMAIN is missing!"
        shell: bash

      # 📌 Install Node.js, Dependencies, and Build Vue App
      - name: Install Dependencies & Build Quasar App
        run: |
          npm install
          quasar clean
          quasar build
        shell: bash

      # 📌 Upload Vue.js (dist/) to Hostinger via FTP
      - name: 🚀 Upload Vue.js (dist/) to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/spa/
          server-dir: /1test/
